Gabarit de guide d'instructions pas à pas de référence
=====================================================
Loïc Fejoz <loic@fejoz.net>
v0.0, Mai 2015
:data-uri:
:icons:
:iconsdir: /usr/share/asciidoc/icons/
:lang: fr
:encoding: utf-8

Opération::
  Renseigner ici le nom de l'opération à effectuer
Composants::
  * lister ici les composants nécessaires
  * composant1
Outils et matériaux::
  * lister les outils nécessaires
  * outil1
Équipements de sécurité requis::
  * lister les equipements de sécurité
  * équipement1

== Étapes

[role='steps withheaders withexplanations']
1. titre
  quoi::
    Étapes importantes
  comment::
    Points importants
  pourquoi::
    Raisons
2. explication
  quoi::
    __Ce qui est fait__ +
    A logical segment of the operation when something happens to advance the work.
  comment::
    __Comment faire__ +
    Tout ce qui dans une étape peut
    - [critical-check]#Faire échouer l'opération#,
    - [quantity-check]#Les quantités à vérifier#,
    - [injury]#Blesser l'opérateur#,
    - [easier]#Faciliter l'opération#, c-à-d les ``trucs'', ``astuces'', timing à respecter, information d'importance.
  pourquoi::
    __Pourquoi faire ainsi__ +
    L'explication du comment faire.
3. étape
  quoi::
    Écrire ici la description de la première étape.
  comment::
    Écrire ici comment réaliser la première étape.
  pourquoi::
    Expliquer ici pourquoi réaliser la première étape ainsi.
    
== Key points reminders

|=======
|[critical-check]#Inspection ou vérification critique# |[quantity-check]#Quantités à vérifier# |[injury]#Blessure et dommages corporels# | [easier]#Facilite le travail#
|=======

[quote, anonyme]
______________________________________________________________
Si l'élève n'a pas appris, l'instructeur n'a pas enseigné.
______________________________________________________________
